### ISSUE TITLE
Submit Score not sending score with request

### ISSUE THREAD

**Issue by rmgalante** [LootLocker/unity-sdk#142]
I notice the following errors occasionally in my console log. I'm passing the score with the request. Notice how the request body doesn't show the score, just a member_id.

ServerRequest POST URL: https://wt5cbcoj.api.lootlocker.io/game/leaderboards/Easy/submit
UnityEngine.Debug:Log (object)
LootLocker.LootLockerBaseServerAPI/<>c__DisplayClass8_0/<<SendRequest>g__coroutine|0>d:MoveNext () (at Assets/LootLockerSDK/Runtime/Client/LootLockerBaseServerAPI.cs:74)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

REQUEST BODY = {"member_id":"**mymemberid**"}
UnityEngine.Debug:Log (object)
LootLocker.LootLockerBaseServerAPI:CreateWebRequest (string,LootLocker.LootLockerServerRequest) (at Assets/LootLockerSDK/Runtime/Client/LootLockerBaseServerAPI.cs:297)
LootLocker.LootLockerBaseServerAPI/<>c__DisplayClass8_0/<<SendRequest>g__coroutine|0>d:MoveNext () (at Assets/LootLockerSDK/Runtime/Client/LootLockerBaseServerAPI.cs:77)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

Server Response: 400 leaderboards/Easy/submit completed in 0.0000 secs.
Response: {"error":"Bad Request","message":"score is required in input","request_id":"9a811fcf-387d-4b4e-8fb9-97f25ad21b62","trace_id":"6ecf1f1a3a8f38eec436369ee32e81bd"}
UnityEngine.Debug:Log (object)
LootLocker.LootLockerBaseServerAPI/<>c__DisplayClass8_0/<<SendRequest>g__coroutine|0>d:MoveNext () (at Assets/LootLockerSDK/Runtime/Client/LootLockerBaseServerAPI.cs:107)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

It's not a showstopper. And it doesn't happen very often.

Update 2023-06-19: It looks like a score of 0 causes this issue.

**Comment by rmgalante** [comment]
I'd like to add details to this problem.

When a player wants to delete his entry, the delete player Api takes up to 30 days to delete the player from the system. The player continues to see his score, even though he requested to be deleted.

So, the app sends a score of 0. That moves the player to the end of the top ten list, and he won't see his score. I suppose I could send a score of 1 in this case. And I will in the next release.

**Comment by kirre-bylund** [comment]
> I'd like to add details to this problem.
> 
> When a player wants to delete his entry, the delete player Api takes up to 30 days to delete the player from the system. The player continues to see his score, even though he requested to be deleted.
> 
> So, the app sends a score of 0. That moves the player to the end of the top ten list, and he won't see his score. I suppose I could send a score of 1 in this case. And I will in the next release.

Please be advised that after deleting a player you should invalidate their session signing them out. A new login or continuous action on that player is seen as a revert of the "delete player" request.

We will look into the 0-score problem.

**Comment by kirre-bylund** [comment]
We have found the issue with 0 scores and will be providing a fix in the next release of the Unity SDK (v1.2.4)
