### ISSUE TITLE
UnityWebRequest timeout handling incorrect

### ISSUE THREAD

**Issue by LongSteve** [LootLocker/unity-sdk#25]
https://github.com/LootLocker/unity-sdk/blob/dd86f336337657eaad4c94cf98fb3b14e86479cf/Runtime/Client/LootLockerBaseServerAPI.cs#L81-L85

When LootLockerBaseServerAPI calls `yield return webRequest.SendWebRequest();` this will not re-enter the co-routine until the request has completed.  This means that the following loop that checks for a timeout value is never entered.  The value of webRequest.isDone will always be true.

Timeouts (eg, in the event of a network disconnect) do still occur, but are timed by the system TCP timeouts, and not controlled by the game code.  

Not an urgent issue, just something I noticed while debugging recently.

**Comment by kirre-bylund** [comment]
Fixed, to be released in v1.1.46
