### ISSUE TITLE
Missing Reference Exception's with Domain Reload disabled

### ISSUE THREAD

**Issue by kyverr** [LootLocker/unity-sdk#69]
When following the tutorial for Guest Login, out-of-the-box LootLocker will throw errors if you're running Unity with domain reload disabled. 

It would be great if the SDK cleared its static references on exiting play mode.
I got around this by calling `LootLockerServerManager.CheckInit();` on Start before making an API call, but it would be fantastic if this was not necessary.

**To replicate:**
- Install SDK into a fresh project
- Unity > Edit > Project Settings > Editor > Enter Play Mode Options checked, uncheck Reload Domain, and uncheck Reload Scene
- Place script that calls SDK on a GameObject i.e.
```
        LootLockerSDKManager.StartGuestSession((response) =>
        {
                Debug.Log(response.success);
        });
```

- Run. (No error, API call works)
- Exit play mode.
- Run. Error occurs. `MissingReferenceException: The object of type 'LootLockerServerManager' has been destroyed but you are still trying to access it.`

This should be quite easy to fix (see: RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration))

**Comment by kirre-bylund** [comment]
https://github.com/LootLocker/unity-sdk/pull/103 <- should be fixed by this
